export const STORAGE_KEY = 'air-agent-settings'
export const DEFAULT_MODEL = 'gpt-4o-mini'
export const DEFAULT_BASE_URL = 'https://api.openai.com/v1'
export const MCP_STORAGE_KEY = 'air-agent-mcp-servers'
export const MCP_SETTINGS_KEY = 'air-agent-mcp-chat-settings'
